"""add error_message to receipts

Revision ID: 051de95fc875
Revises: b294910e145e
Create Date: 2026-04-02 14:22:36.268553

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '051de95fc875'
down_revision: Union[str, None] = 'b294910e145e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('receipts', sa.Column('error_message', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('receipts', 'error_message')
    # ### end Alembic commands ###
