"""add email verification to users

Revision ID: 676eac4a8b56
Revises: b3878b55e0b3
Create Date: 2026-04-09 16:17:00.471480

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '676eac4a8b56'
down_revision: Union[str, None] = 'b3878b55e0b3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
