"""add model_used to receipts

Revision ID: b209d41a28cd
Revises: 051de95fc875
Create Date: 2026-04-02 14:36:19.647804

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'b209d41a28cd'
down_revision: Union[str, None] = '051de95fc875'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('receipts', sa.Column('model_used', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('receipts', 'model_used')
    # ### end Alembic commands ###
