"""add email verification to users

Revision ID: b3878b55e0b3
Revises: c5c9fb813bf0
Create Date: 2026-04-06 22:09:32.520831

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'b3878b55e0b3'
down_revision: Union[str, None] = 'c5c9fb813bf0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
