"""add receipt batches table

Revision ID: bc7e0f147051
Revises: b209d41a28cd
Create Date: 2026-04-05 21:05:09.987969

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'bc7e0f147051'
down_revision: Union[str, None] = 'b209d41a28cd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('receipt_batches',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('total_count', sa.Integer(), nullable=False),
    sa.Column('completed_count', sa.Integer(), nullable=True),
    sa.Column('failed_count', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_receipt_batches_user_id'), 'receipt_batches', ['user_id'], unique=False)
    op.add_column('receipts', sa.Column('batch_id', sa.UUID(), nullable=True))
    op.create_index(op.f('ix_receipts_batch_id'), 'receipts', ['batch_id'], unique=False)
    op.create_foreign_key(None, 'receipts', 'receipt_batches', ['batch_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'receipts', type_='foreignkey')
    op.drop_index(op.f('ix_receipts_batch_id'), table_name='receipts')
    op.drop_column('receipts', 'batch_id')
    op.drop_index(op.f('ix_receipt_batches_user_id'), table_name='receipt_batches')
    op.drop_table('receipt_batches')
    # ### end Alembic commands ###
