"""add email verification to users

Revision ID: c5c9fb813bf0
Revises: bc7e0f147051
Create Date: 2026-04-06 22:00:58.577225

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'c5c9fb813bf0'
down_revision: Union[str, None] = 'bc7e0f147051'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('verification_token', sa.String(), nullable=True))
    op.add_column('users', sa.Column('is_verified', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'is_verified')
    op.drop_column('users', 'verification_token')
    # ### end Alembic commands ###
