"""add email verification to users

Revision ID: ec087a1b4dcd
Revises: 676eac4a8b56
Create Date: 2026-04-09 16:20:35.526458

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'ec087a1b4dcd'
down_revision: Union[str, None] = '676eac4a8b56'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
